name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8

    - name: create key.properties file
      run: cp app/key.properties.example app/key.properties

    - name: create keystore file
      run: keytool -genkey -v -keystore app/debug.keystore -alias AndroidDebugKey -keyalg RSA -keysize 2048 -validity 1 -storepass android -keypass android -dname "cn=TEST, ou=TEST, o=TEST, c=TE"

    - name: build with gradle
      run: ./gradlew assembleRelease

    - name: list build files
      run: |
        ls -alh app/build/outputs/apk/
        ls -alh app/build/outputs/apk/release/

#    - name: upload artifact
#      uses: actions/upload-artifact@master
#      with:
#        name: seadroid apk
#        path: app/build/outputs/apk

    - name: gzip
      run: |
        tar -czvf seadroid.tar.gz app/build/outputs/apk/
        ls -alh seadroid.tar.gz

    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
    - name: upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./seadroid.tar.gz
        asset_name: seadroid.tar.gz
        asset_content_type: application/x-gzip

#    - name: Upload to release
#      uses: JasonEtco/upload-to-release@master
#      with:
#        args: seadroid.tar.gz application/octet-stream
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
