name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8

    - name: create key.properties file
      run: cp app/key.properties.example app/key.properties

    - name: create keystore file
      run: keytool -genkey -v -keystore app/debug.keystore -alias AndroidDebugKey -keyalg RSA -keysize 2048 -validity 1 -storepass android -keypass android -dname "cn=TEST, ou=TEST, o=TEST, c=TE"

    - name: build with gradle
      run: ./gradlew assembleRelease

    - name: list build files
      run: tree app/build/outputs/apk/

    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: seadroid apk
        path: app/build/outputs/apk
